### ISSUE TITLE
How to receive sms message 

### ISSUE THREAD

**Issue by ranggaaprilio** [styryl/node-goip#1]
Hello,i want to ask about how to recive sms from goip, i used goip 4.

I see you have a serverFactory to create a server for listener,but i dont understand how the serverfactory can connect to goip 4 IP

Please help me..

**Comment by styryl** [comment]
The server does not connect to the gsm goip gateway, goip connects to the server. You need to change the settings in the goip configuration panel. Receiving SMS messages is described in the documentation.

GOIP manual http://static.dbltek.com/GoIP+Series+User+Manual+V1.5-aidloBqmKioSRrimmrrini.pdf

**Comment by ranggaaprilio** [comment]
i had run this app in port 3001
![image](https://user-images.githubusercontent.com/50992993/100814968-7db89980-3475-11eb-87c4-9669b3a00823.png)

and in sms configuration, i was set sms server IP to my computer's IP who running node-goip server in port 3001
![image](https://user-images.githubusercontent.com/50992993/100815267-164f1980-3476-11eb-9959-efc0477a1629.png)


but i still can't Receive the messages, please correct me if i'm wrong..

**Comment by ranggaaprilio** [comment]
thanks for a help,it is working perfectly now.. :)
