### ISSUE TITLE
i had run this app in port 3001

### ISSUE THREAD

**Issue by andihoerudin24** [styryl/node-goip#3]
i had run this app in port 3001
![image](https://user-images.githubusercontent.com/50992993/100814968-7db89980-3475-11eb-87c4-9669b3a00823.png)

and in sms configuration, i was set sms server IP to my computer's IP who running node-goip server in port 3001
![image](https://user-images.githubusercontent.com/50992993/100815267-164f1980-3476-11eb-9959-efc0477a1629.png)

but i still can't Receive the messages, please correct me if i'm wrong..

_Originally posted by @ranggaaprilio in https://github.com/styryl/node-goip/issues/1#issuecomment-736922791_

**Comment by styryl** [comment]
The server configuration looks fine. Set in goip SMS Client ID and Password. The problem may be with your network configuration.

**Comment by andihoerudin24** [comment]
Can I ask for a reference how to set the client ID?

**Comment by styryl** [comment]
Whatever, there is no special specification. For example: client id: goiptest and password: goiptest

**Comment by andihoerudin24** [comment]
okay thanks for the information, I have successfully configured the goib route using the package you created, both for receiving sms and sending sms, thank you very much
